@namespace PegExamples
@classname MathExpressionParser
@using System.Globalization

addition<SyntaxNode> 
    = lhs:multiplication _ '+' _ rhs:addition
        { new AdditionNode(lhs,rhs) }
    / multiplication

multiplication<SyntaxNode> 
    = lhs:number _ '*' _ rhs:multiplication
        { new MultiplicationNode(lhs,rhs) }
    / number

number<NumberNode> 
	= value:("" [0-9]+) { new NumberNode(decimal.Parse(value)) }

_ = [ \t\r\n]*